version: '3.8'

services:
  mongo:
    image: bitnami/mongodb:latest
    container_name: db_ghani_betest
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app_network

  redis:
    image: redis
    container_name: redis_ghani_betest
    ports:
      - "6379:6379"
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: ms-ghani-betest
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://root:example@mongo:27017/db_ghani_betest?authSource=admin"
      JWT_SECRET: "your_jwt_secret"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      PORT: 3000
    networks:
      - app_network
    depends_on:
      - mongo
      - redis

networks:
  app_network:
    name: app_network
    driver: bridge
volumes:
  mongo-data:
